### ISSUE TITLE
python-future.org is inaccessible via HTTPS

### ISSUE THREAD

**Issue by QuLogic** [PythonCharmers/python-future#143] opened 2015-05-06 05:00 UTC
Attempting to navigate to https://python-future.org/ does not work because it is serving the certificate for pythoncharmers.com, which is weird since pythoncharmers.com does not respond at all over HTTPS.

**Comment by yan12125** [comment] 2016-10-09 12:26
Yes, and PyPI's homepage points to it:
https://github.com/PythonCharmers/python-future/blob/master/setup.py#L99

**Comment by jmadler** [comment] 2019-05-06 15:06
Dupe of #358

**Closed by jmadler** 2019-05-06 15:06 UTC
