### ISSUE TITLE
HTTPS to python-future.org (https://python-future.org) down

### ISSUE THREAD

**Issue by cooperlees** [PythonCharmers/python-future#324] opened 2018-02-01 23:53 UTC
Your website's HTTPS is down. Didn't know how else to notify.

Can ping 192.81.210.173 ahd http. Just not https.

Your pypi links (thus setup.py) point @ https.

**Comment by cooperlees** [comment] 2018-02-01 23:56
https://github.com/PythonCharmers/python-future/pull/325 is up.

**Comment by jaraco** [comment] 2018-08-31 13:56
Better would be to serve on HTTPS.

**Comment by cooperlees** [comment] 2018-08-31 15:31
Totally, but it would be nice to have working links too in the meantime.

There is obviously no urgency here ...

**Comment by jmadler** [comment] 2019-05-06 15:06
Dupe of #358

**Closed by jmadler** 2019-05-06 15:06 UTC
