### ISSUE TITLE
fix_next is not listed as a stage 2 fixer

### ISSUE THREAD

**Issue by elistevens** [PythonCharmers/python-future#527] opened 2019-11-06 01:25 UTC
On the page https://python-future.org/futurize.html#stage-1-safe-fixes it says near the bottom of the section: "fix_next is applied in stage 2."

This seems to be true.

However, lower in the page the "The complete list of fixers applied in Stage 2 is:" list does not include fix_next.

Can someone please audit the list of fixers for both stage 1 and 2?

I'm currently working around this with 

```
fixes_to_run="`python -c 'import libfuturize.fixes as f; print \"\n\".join(f.lib2to3_fix_names_stage1 )'`
`python -c 'import libfuturize.fixes as f; print \"\n\".join(f.libfuturize_fix_names_stage1)'`
`python -c 'import libfuturize.fixes as f; print \"\n\".join(f.lib2to3_fix_names_stage2 )'`
`python -c 'import libfuturize.fixes as f; print \"\n\".join(f.libfuturize_fix_names_stage2)'`"
```

**Comment by bhrutledge** [comment] 2019-11-20 16:28
Possible duplicate of #477?

**Comment by sfdye** [comment] 2020-06-13 02:50
Yes let's merge with #477

**Comment by sfdye** [comment] 2020-06-13 02:51
I've verified it's in the latest docs build locally
![image](https://user-images.githubusercontent.com/1016390/84558227-cfeced80-ad63-11ea-8d05-ecba7a51d070.png)

**Closed by sfdye** 2020-06-13 02:50 UTC
